EBombo/ebombo-events

- src/firebase/index.js
- src/pages/home/index.js
- src/pages/library/ListGameView.js
- src/pages/library/games/_gameId/view/index.js
Se corrigió la ruta de la creación de un lobby
Se consume el API RED
> redirect to lobby

- src/firebase/config.json
- src/pages/home/index.js
- src/pages/library/ListGameView.js
- src/pages/library/games/_gameId/view/index.js
Se agrega el nombre del juego en la ruta
El proposito es redireccionar por ruta a un proyecto [juego]:
***path => project****
ebombo.io/ => bombo-games [login]
ebombo.io/bingo/... => Bingo
ebombo.io/hanged/.... => Hanged
ebombo.io/other/..... => Other
> redirect to create lobby with game name

- cloudbuild.yaml
docker repository & clodu run renamed
> repository renamed

- src/pages/admin/games/_gameId/index.js
Adding title when creating/editing game
> Addint title

- src/pages/subscriptions/Plans.js
adding redirect to subcription button
> adding redirect to subcription button

- src/pages/library/ModalNewGame.js
- src/pages/library/games/_gameId/Hanged.js
- src/pages/library/games/_gameId/index.js
Form to create game with request
> Create game hanged

- pages/about-us/index.js
- pages/founders/index.js
- src/components/Footer.js
- src/components/Navbar.js
- src/pages/about-us/index.js
- src/pages/founders/index.js
Landing founders and about us pages
> New Landing views

- src/pages/library/games/_gameId/Bingo.js
- src/pages/library/games/_gameId/Hanged.js
- src/pages/library/games/_gameId/index.js
Showing error when failed and adding cover image url
> Create Hanged Game

- src/pages/subscriptions/Plans.js
- src/pages/subscriptions/PlansTable.js
> Most popular

- src/pages/home/comments/Comments.js
Hidding scrollbar from mobile and showing for desktop
> Scrollbar Comments

- src/pages/subscriptions/Plans.js
Adding line break for mobile and tablet
> adding line break

- src/components/Navbar.js
- src/pages/home/Products.js
- src/pages/subscriptions/Plans.js
Image issue and plan content issues
> Solving issues

- src/pages/home/ContactForm.js
solving style problem when the page first load
> refactorgin contact form

- src/pages/users/_userId/Privacy.js
- src/pages/users/_userId/index.js
- src/theme/GlobalStyle.js
- src/theme/themes.js
new section privacy in the profile
> Profile Privacy

- src/pages/library/games/_gameId/Roulette.js
Fixing variable names and refactoring isLive useState
> Fixing edit roulette game

- src/pages/library/games/_gameId/Roulette.js
making variable name to be more general
> Updating variable name

- src/pages/home/ContactForm.js
> Adding contact image

- src/pages/library/games/_gameId/Roulette.js
adding small description to roulette
> Live description

- src/pages/library/ListGameView.js
Adding game icon in list game view
> List game view

- src/pages/library/ListGameView.js
changing color and adding font
> font color

- src/components/form/Select.js
- src/pages/login/index.js
- src/pages/register/index.js
- tailwind.config.js
> Redesign login and register

- src/pages/library/games/_gameId/view/UsersView.js
- src/pages/library/games/_gameId/view/index.js
Preview users inscriptions by link
> Preview Users

- src/components/common/ModalMove.js
- src/pages/library/games/_gameId/index.js
- src/pages/library/games/_gameId/view/SideBar.js
- src/pages/library/games/_gameId/view/index.js
Fixing Modal Move and Buttons Preview game
> Fixs Move and Buttons

- src/pages/library/games/_gameId/Trivia.js
Fixes select time string -> number
Fixes validation of in-the-middle not valid questions
> fix select time and questions validation

- pages/library/games/[gameId]/index.js
- src/constants/responsive.js
- src/pages/library/games/_gameId/Bingo.js
- src/pages/library/games/_gameId/Hanged.js
- src/pages/library/games/_gameId/Roulette.js
- src/pages/library/games/_gameId/Trivia.js
- src/pages/library/games/_gameId/TriviaQuestion.js
- src/pages/library/games/_gameId/index.js
> New Design Create Games

- pages/_app.js
- pages/library/events/[eventId]/releases/[releaseId]/index.js
- src/hooks/acl/acls.json
- src/pages/library/ListGameView.js
- src/pages/library/events/_eventId/EventStepFour.js
- src/pages/library/events/_eventId/EventStepOne.js
- src/pages/library/events/_eventId/EventStepTwo.js
- src/pages/library/events/_eventId/index.js
- src/pages/library/events/_eventId/releases/_releaseId/index.js
- src/pages/library/events/_eventId/view/index.js
- src/pages/library/events/index.js
- src/theme/GlobalStyle.js
> Creating release

- src/pages/library/events/_eventId/EventStepFour.js
- src/pages/library/events/_eventId/EventStepOne.js
- src/pages/library/events/_eventId/EventStepThree.js
- src/pages/library/events/_eventId/EventStepTwo.js
- src/pages/library/events/_eventId/UserCreateEvent.js
- src/pages/library/events/_eventId/index.js
- src/pages/library/events/_eventId/releases/_releaseId/index.js
- src/pages/library/events/_eventId/view/index.js
> Fixing event

- public/locales/es.json
- src/pages/corporate-events/index.js
> feedback corporate events

- src/pages/library/ListGameView.js
https://www.notion.so/ebombo/Juegos-de-no-se-pueden-borrar-89c3d738f4d04885baa47e0ad682d531
> be able to delete a game

- src/components/form/Input.js
- src/pages/contact/index.js
- src/pages/library/games/_gameId/TriviaQuestion.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=0ddde3d14df94cdfa72d1b674b38de19
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=1f441e7834bc4629b14fe99f08b79d89
> Feedback contact and input color

- src/pages/corporate-events/index.js
- src/pages/on-boarding/index.js
- src/pages/team-building/index.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=580e9f86be374b9d8a53286459551baa
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=c1a340d01a494a5b8fb47af5633355da
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=580e9f86be374b9d8a53286459551baa
> Feedback use cases pages

- package-lock.json
- src/pages/library/ListGameView.js
- src/pages/library/games/_gameId/TriviaQuestion.js
https://www.notion.so/ebombo/Dailies-Producto-Tech-f3138494e45c4267992fdd9a23b1641b?p=78867bcb91634a539a00fb3833adfc6f
> Delete answer in short answer 

- src/components/form/Input.js
Allowing to past a prefix to the input
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=bcf05e469e774d49b7f0f5dd93a1d2f7
> Adding prefix to input

- src/pages/library/games/_gameId/TriviaQuestion.js
change color icon to black
https://www.notion.so/ebombo/Dailies-Producto-Tech-f3138494e45c4267992fdd9a23b1641b?p=78867bcb91634a539a00fb3833adfc6f
> color icon

- src/components/Navbar.js
- src/components/SubscriptionPlans.js
- src/components/form/Switch.js
- src/components/nav/DesktopNav.js
- src/components/nav/TabletNav.js
- src/pages/companies/_companyId/EditCompany.js
- src/pages/contact/index.js
- src/pages/library/events/_eventId/EventStepFour.js
- src/pages/library/games/_gameId/ModalSettings.js
- src/theme/GlobalStyle.js
Refactoring create event
https://www.notion.so/ebombo/Dailies-Producto-Tech-f3138494e45c4267992fdd9a23b1641b?p=e84cfbe397eb4b6a8e3ed50e079712ae
https://www.notion.so/ebombo/Dailies-Producto-Tech-f3138494e45c4267992fdd9a23b1641b?p=1b0facf760564c35bd55af1009c6eae8
https://www.notion.so/ebombo/Dailies-Producto-Tech-f3138494e45c4267992fdd9a23b1641b?p=f257c63769d84ca2b816294b99e5c629
> New Create Event

- pages/library/events/[eventId]/index.js
- src/pages/events/eventId/index.js
- src/pages/library/events/_eventId/index.js
https://www.notion.so/ebombo/Nab-bar-Crear-evento-6123d58c76634b4ba6dd7b5631363196
> new navbar

- pages/kick-off/index.js
- public/locales/en.json
- public/locales/es.json
- src/components/Navbar.js
- src/components/common/DataList.js
- src/hooks/useTranslation.js
- src/pages/kick-off/index.js
https://www.notion.so/ebombo/Landing-Kick-Off-6069b6584d214eeb9916aabda3e88606
> new page kick off

- src/pages/library/games/_gameId/Trivia.js
https://www.notion.so/ebombo/Aca-la-imagen-sale-pixeleada-despues-de-cargarla-43821cffcdf14d738b595f4061ddca44
> trivia new img size

- src/pages/companies/_companyId/Billing.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=ac806f7d5042488b9ccf92f83e60ad83
> disabling billing flag

- firestore.indexes.json
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=ac806f7d5042488b9ccf92f83e60ad83
> added index for subscriptions

- public/locales/en/pages/events.json
- public/locales/es/pages/events.json
- src/pages/events/eventId/ResumeEvent.js
- src/pages/library/events/index.js
https://www.notion.so/ebombo/Creaci-n-de-eventos-SIN-usuario-part-2-eaf564cd363e4600a7978ed8cf0c9e5a
> feedbacks create events

- src/pages/library/games/_gameId/view/TriviaView.js
https://www.notion.so/ebombo/La-im-gen-tapa-el-vector-cb8685b65ebb4681a46c2b56e8d0adea
> La imágen tapa el vector

- src/pages/home/Products.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?p=8a8ae4077e3b4df7942f1c13bf2541bf
> add margin

- public/locales/en.json
- public/locales/es.json
- src/pages/admin/users/index.js
- src/pages/reports/index.js
- src/pages/reports/lobbies/_lobbyId/ModalRanking.js
- src/pages/reports/lobbies/_lobbyId/ModalUserAnswers.js
- src/pages/reports/lobbies/_lobbyId/TriviaReport.js
- src/pages/reports/lobbies/_lobbyId/TriviaResume.js
- src/pages/reports/lobbies/_lobbyId/TriviaUsers.js
https://www.notion.so/ebombo/Feedback-Reportes-Trivia-5b51cb086ee747f7abbd2ebb14f203f9
https://www.notion.so/ebombo/Feedback-Reportes-Trivia-071e3741448c49b09fdcacb84b5924f2
> Feedback trivia

- public/locales/en/pages/events.json
- public/locales/es/pages/events.json
- src/pages/admin/contacts/index.js
- src/pages/events/eventId/DetailsEvent.js
- src/pages/events/eventId/ResumeEvent.js
- src/pages/events/eventId/dataList.js
https://www.notion.so/ebombo/Creaci-n-de-eventos-SIN-usuario-eaf564cd363e4600a7978ed8cf0c9e5a
> Creación de eventos SIN usuario

- src/components/form/Select.js
- src/constants/sizes.js
- src/pages/admin/games/_gameId/index.js
- src/pages/admin/games/index.js
- src/pages/library/ModalNewGame.js
https://www.notion.so/ebombo/Agrupaci-n-de-juegos-789f1ce0d00e4770bf6e62f34208892d
> agrupacion de juegos

- src/pages/home/Products.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?v=0b95bf30124349e780ecbcaa0b569d01&p=e9ebabef4c4d4f33b4e28dfa3d75199f
> set spacing

- src/pages/admin/games/_gameId/index.js
https://www.notion.so/ebombo/Agrupaci-n-de-juegos-789f1ce0d00e4770bf6e62f34208892d
> fix create game with typeGame

- src/components/common/PlansPrices.js
- src/pages/companies/_companyId/Billing.js
- src/pages/subscriptions/PlansTable.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?v=ec3114d9344d40789fec0947275ed11c&p=dbbde045935941bd9317706efba7cfdb
> Issue/invoicing 3.0

- src/pages/library/ModalNewGame.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?v=ec3114d9344d40789fec0947275ed11c&p=283b15395bf34abeb8d486de558f929d
> replace reaction for non-games

- src/pages/library/ListGameView.js
- src/pages/library/games/_gameId/view/index.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?v=ec3114d9344d40789fec0947275ed11c&p=340367a6a33f401e8ab57f0c9fe47750
> enable language preference for roulette

- public/locales/en.json
- public/locales/es.json
- src/components/common/DataList.js
- src/hooks/useStripePlans.js
- src/pages/companies/_companyId/index.js
- src/pages/subscriptions/PlansTable.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?v=ec3114d9344d40789fec0947275ed11c&p=954a4c00795a4f8f8766136a841c1f8b
> Feature/invoicing 3.0

- src/pages/library/games/_gameId/TriviaQuestion.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?v=ec3114d9344d40789fec0947275ed11c&p=e8132b8ad8914c418d34a916fb6bc605
> fix update regex

- public/locales/en.json
- public/locales/es.json
- src/pages/reports/lobbies/_lobbyId/BingoReport.js
- src/pages/reports/lobbies/_lobbyId/BingoResume.js
- src/pages/reports/lobbies/_lobbyId/BingoUsers.js
- src/pages/reports/lobbies/_lobbyId/ModalBingoRounds.js
- src/pages/reports/lobbies/_lobbyId/ModalUserCards.js
https://www.notion.so/ebombo/Reporte-Bingo-e67aababc16c4ac4adb40b0bbeeb92bf
> Bingo report

- public/locales/es.json
- src/hooks/useTranslation.js
- src/utils/cookieUtils.js
- src/utils/index.js
https://www.notion.so/ebombo/TECH-TASK-8ab20c64c6fe427385e6247091f186a8?v=ec3114d9344d40789fec0947275ed11c&p=ad0162967d4f4a74a11390163b49d11d
> set locale

- pages/events/[eventId]/index.js
- src/pages/library/events/index.js
https://www.notion.so/ebombo/Crear-evento-ebombo-d7885341c2e5431aa0ca49d8994e4cff
> fix nav create event

- src/pages/pricing/index.js
- src/pages/subscriptions/PlansTable.js
> fixing plan table in mobile
